spring:
  application:
    name: Vendor
server:
  port: 8080

# MongoDB Configuration
mongo:
  host: localhost
  port: 27017
  dbName: test
  collectionName: employees

# Postgres Configuration
postgres:
  host: localhost
  port: 5432
  dbName: test
  username: postgres
  password: postgres
  driver: org.postgresql.Driver

# MySQL Configuration
mysql:
  host: localhost
  port: 3309
  dbName: test
  username: root
  password:
  driver: com.mysql.cj.jdbc.Driver

#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer